<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Language;
use Doctrine\ORM\Query;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray()
    {
        $qb = $this->createQueryBuilder('l')
            ->select('l, t, tr')
            ->leftJoin('l.translationKeys', 't')
            ->leftJoin('t.translations', 'tr')
            ->where('tr.language = l');
        return $qb->getQuery()->getArrayResult();
    }
}
