<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TranslationKey;

/**
 * TranslationKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationKeyRepository extends BaseAppRepository
{
    public function findAllAsArray()
    {
        $qb = $this->createQueryBuilder('tr')
            ->select('tr');
        return $qb->getQuery()->getArrayResult();
    }
}
